function getAvailableMajors() {
return [
"Accounting",
"Accounting Technology/Technician and Bookkeeping",
"Accounting and Business/Management",
"Accounting and Finance",
"Acting",
"Actuarial Science",
"Administration of Special Education",
"Administrative Assistant and Secretarial Science, General",
"Advertising",
"Aeronautics/Aviation/Aerospace Science and Technology, General",
"African Languages, Literatures, and Linguistics",
"African Studies",
"African-American/Black Studies",
"Airline/Commercial/Professional Pilot and Flight Crew",
"Algebra and Number Theory",
"American History (United States)",
"American Government and Politics (United States)",
"American Literature (United States)",
"Analytical Chemistry",
"Ancient Near Eastern and Biblical Languages, Literatures, and Linguistics",
"Ancient/Classical Greek Language and Literature",
"Animation, Interactive Technology, Video Graphics and Special Effects",
"Anthropology",
"Apparel and Accessories Marketing Operations",
"Apparel and Textiles, General",
"Applied Economics",
"Applied Mathematics, General",
"Aquatic Biology/Limnology",
"Arabic Language and Literature",
"Area Studies, Other",
"Art",
"Art History, Criticism and Conservation",
"Art Teacher Education",
"Art/Art Studies, General",
"Artificial Intelligence",
"Asian Studies/Civilization",
"Astronomy",
"Astronomy and Astrophysics, Other",
"Astrophysics",
"Athletic Training/Trainer",
"Atmospheric Sciences and Meteorology, General",
"Atomic/Molecular Physics",
"Audiology/Audiologist",
"Audiology/Audiologist and Speech-Language Pathology/Pathologist",
"Audiovisual Communications Technologies/Technicians, Other",
"Aviation/Airway Management and Operations",
"Ballet",
"Behavioral Sciences",
"Biochemistry",
"Biochemistry and Molecular Biology",
"Biochemistry, Biophysics and Molecular Biology, Other",
"Bioengineering and Biomedical Engineering",
"Bioinformatics",
"Biological and Biomedical Sciences, Other",
"Biological and Physical Sciences",
"Biology Teacher Education",
"Biology/Biological Sciences, General",
"Biomedical Sciences, General",
"Biotechnology",
"Botany/Plant Biology",
"Broadcast Journalism",
"Business Administration and Management, General",
"Business, Management, Marketing, and Related Support Services, Other",
"Business/Managerial Economics",
"Cell Physiology",
"Cell/Cellular and Molecular Biology",
"Ceramic Arts and Ceramics",
"Chemical Engineering",
"Chemistry Teacher Education",
"Chemistry, General",
"Chemistry, Other",
"Child Development",
"Cinematography and Film/Video Production",
"Civil Engineering, General",
"Classics and Classical Languages, Literatures, and Linguistics, General",
"Classics and Classical Languages, Literatures, and Linguistics, Other",
"Clinical Psychology",
"College Student Counseling and Personnel Services",
"Commercial Photography",
"Communication Disorders Sciences and Services, Other",
"Communication and Media Studies, Other",
"Communication, Journalism, and Related Programs, Other",
"Community Health Services/Liaison/Counseling",
"Computational Mathematics",
"Computer Engineering, General",
"Computer Games and Programming Skills",
"Computer Programming, Other",
"Computer Science",
"Computer Software Engineering",
"Computer Systems Networking and Telecommunications",
"Computer Teacher Education",
"Computer and Information Sciences, General",
"Conservation Biology",
"Consumer Merchandising/Retailing Management",
"Counselor Education/School Counseling and Guidance Services",
"Creative Writing",
"Criminal Justice/Police Science",
"Criminology",
"Curriculum and Instruction",
"Dance, General",
"Development Economics and International Development",
"Dietetics/Dietitian",
"Digital Communication and Media/Multimedia",
"Directing and Theatrical Production",
"Drama and Dramatics/Theatre Arts, General",
"Dramatic/Theatre Arts and Stagecraft, Other",
"Early Childhood Education and Teaching",
"East Asian Studies",
"Ecology and Evolutionary Biology",
"Economics, General",
"Education, General",
"Education/Teaching of Indiv. in Early Childhood Special Education Programs",
"Educational Administration and Supervision, Other",
"Educational Evaluation and Research",
"Educational Leadership and Administration, General",
"Educational Statistics and Research Methods",
"Educational/Instructional Technology",
"Electrical and Electronics Engineering",
"Elementary Education and Teaching",
"Engineering Technology, General",
"Engineering, General",
"Engineering, Other",
"Engineering/Industrial Management",
"English Language and Literature, General",
"English/Language Arts Teacher Education",
"Environmental Biology",
"Environmental Health",
"Environmental Science",
"Environmental Studies",
"Equestrian/Equine Studies",
"Ethnic Studies",
"European History",
"European Studies/Civilization",
"Evolutionary Biology",
"Exercise Physiology",
"Experimental Psychology",
"Family Practice Nurse/Nursing",
"Family Resource Management Studies, General",
"Family and Consumer Economics and Related Services, Other",
"Family and Consumer Sciences/Human Sciences, General",
"Film/Cinema/Video Studies",
"Film/Video and Photographic Arts, Other",
"Finance, General",
"Financial Planning and Services",
"Fine/Studio Arts, General",
"Foods, Nutrition, and Wellness Studies, General",
"Foodservice Systems Administration/Management",
"Foreign Languages and Literatures, General",
"Foreign Languages, Literatures, and Linguistics, Other",
"Forensic Science and Technology",
"French Language Teacher Education",
"French Language and Literature",
"General Merchandising, Sales, and Related Marketing Operations, Other",
"Geographic Information Science and Cartography",
"Geography",
"Geography, Other",
"Geological and Earth Sciences/Geosciences, Other",
"Geology/Earth Science, General",
"German Language Teacher Education",
"German Language and Literature",
"Gerontology",
"Graphic Design",
"Health Communication",
"Health Professions and Related Clinical Sciences, Other",
"Health Services Administration",
"Health and Physical Education/Fitness, General",
"Health and Physical Education/Fitness, Other",
"Health/Health Care Administration/Management",
"Higher Education/Higher Education Administration",
"History, General",
"History, Other",
"Hospital and Health Care Facilities Administration/Management",
"Hospitality and Recreation Marketing Operations",
"Housing and Human Environments, General",
"Human Development and Family Studies, General",
"Human Resources Management/Personnel Administration, General",
"Humanities/Humanistic Studies",
"Indonesian/Malay Languages and Literatures",
"Industrial Engineering",
"Industrial Technology/Technician",
"Industrial and Organizational Psychology",
"Information Technology",
"Inorganic Chemistry",
"Intercultural/Multicultural and Diversity Studies",
"Interior Architecture",
"Intermedia/Multimedia",
"International Business/Trade/Commerce",
"International Relations and Affairs",
"International/Global Studies",
"Islamic Studies",
"Jewish/Judaic Studies",
"Journalism",
"Junior High/Intermediate/Middle School Education and Teaching",
"Keyboard Instruments",
"Kinesiology and Exercise Science",
"Latin American Studies",
"Latin Language and Literature",
"Legal Studies, General",
"Liberal Arts and Sciences, General Studies and Humanities, Other",
"Liberal Arts and Sciences/Liberal Studies",
"Linguistics",
"Management Information Systems, General",
"Marine Biology and Biological Oceanography",
"Marketing/Marketing Management, General",
"Mass Communication/Media Studies",
"Mathematical Statistics and Probability",
"Mathematics Teacher Education",
"Mathematics and Computer Science",
"Mathematics and Statistics, Other",
"Mathematics, General",
"Mechanical Engineering",
"Medical Microbiology and Bacteriology",
"Meteorology",
"Microbiology, General",
"Mining and Mineral Engineering",
"Molecular Biochemistry",
"Molecular Biology",
"Multi-/Interdisciplinary Studies, Other",
"Music",
"Music History, Literature, and Theory",
"Music Pedagogy",
"Music Performance, General",
"Music Teacher Education",
"Music Theory and Composition",
"Music Therapy/Therapist",
"Music, General",
"Music, Other",
"Neurobiology and Anatomy",
"Neuroscience",
"Nuclear Physics",
"Nursing Administration",
"Nutrition Sciences",
"Occupational Health and Industrial Hygiene",
"Organic Chemistry",
"Organizational Communication, General",
"Osteopathic Medicine/Osteopathy",
"Painting",
"Parks, Recreation and Leisure Studies",
"Parks, Recreation, Leisure, and Fitness Studies, Other",
"Peace Studies and Conflict Resolution",
"Philosophy",
"Photography",
"Photojournalism",
"Physical Education Teaching and Coaching",
"Physical Therapy/Therapist",
"Physics, General",
"Plant Molecular Biology",
"Playwriting and Screenwriting",
"Political Communication",
"Political Science and Government, General",
"Pre-Dentistry Studies",
"Pre-Medicine/Pre-Medical Studies",
"Pre-Nursing Studies",
"Pre-Pharmacy Studies",
"Pre-Veterinary Studies",
"Printmaking",
"Psychology, General",
"Public Administration",
"Public Administration and Social Service Professions, Other",
"Public Health, General",
"Public Relations/Image Management",
"Radio and Television",
"Radio and Television Broadcasting Technology/Technician",
"Radio, Television, and Digital Communication, Other",
"Reading Teacher Education",
"Registered Nursing/Registered Nurse",
"Religion/Religious Studies",
"Restaurant/Food Services Management",
"Rhetoric and Composition",
"Romance Languages, Literatures, and Linguistics, Other",
"Russian Language and Literature",
"Science Teacher Education/General Science Teacher Education",
"Sculpture",
"Secondary Education and Teaching",
"Secondary School Administration/Principalship",
"Social Science Teacher Education",
"Social Sciences, General",
"Social Studies Teacher Education",
"Social Work",
"Social and Philosophical Foundations of Education",
"Sociology",
"Southeast Asian Studies",
"Spanish Language Teacher Education",
"Spanish Language and Literature",
"Special Education and Teaching, General",
"Speech Communication and Rhetoric",
"Speech-Language Pathology/Pathologist",
"Sport and Fitness Administration/Management",
"Stringed Instruments",
"Systems Engineering",
"Teaching English as a Second or Foreign Language/ESL Language Instructor",
"Technical Theatre/Theatre Design and Technology",
"Theatre Literature, History and Criticism",
"Theatre/Theater",
"Theatre/Theatre Arts Management",
"Tourism and Travel Services Management",
"Urban Studies/Affairs",
"Visual and Performing Arts, General",
"Voice and Opera",
"Web/Multimedia Management and Webmaster",
"Wildlife Biology",
"Womens Studies",
"Writing",
"Writing, General",
"Zoology/Animal Biology"
];
}